[
  ./base/nix
  ./base/tmux
  ./base/users
  ./base/wifi
  ./desktop/gdm
  ./desktop/gnome
  ./desktop/hyprland
  ./networking/sync
  ./networking/wireguard
  ./servers/auth
  ./servers/binary-cache
  ./servers/ca
  ./servers/cloud
  ./servers/code
  ./servers/feeds
  ./servers/graphs
  ./servers/mail
  ./servers/media
  ./servers/meet
  ./servers/minecraft
  ./servers/office
  ./servers/paperless
  ./servers/passwords
  ./servers/photos
  ./servers/player
  ./servers/radiogaga
  ./servers/spotify
  ./servers/uptime
  ./servers/virtual-hosts
  ./servers/websites
]
